### ISSUE TITLE
TypeError: An update must have the same type as the original shared variable

### ISSUE THREAD

**Issue by akkikiki** [bdhingra/tweet2vec#2]
Hello, I am new to Theano, so I might be asking an obvious question, but I keep on encountering the following error. Does anybody know the solution to this problem?
I am running in a CPU mode, so I added `THEANO_FLAGS=device=cpu` to tweet2vec_trainer.sh.

```
$ sh tweet2vec_trainer.sh 
Training...
Preparing Data...
Building Model...
Building network...
/usr/local/lib/python2.7/site-packages/theano/scan_module/scan.py:1019: Warning: In the strict mode, all neccessary shared variables must be passed as a part of non_sequences
  'must be passed as a part of non_sequences', Warning)
Computing updates...
Compiling theano functions...
Traceback (most recent call last):
  File "char.py", line 231, in <module>
    main(sys.argv[1],sys.argv[2],sys.argv[3])
  File "char.py", line 129, in main
    train = theano.function(inps,cost,updates=updates)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/function.py", line 316, in function
    output_keys=output_keys)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 499, in pfunc
    no_default_updates=no_default_updates)
  File "/usr/local/lib/python2.7/site-packages/theano/compile/pfunc.py", line 215, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=Wc, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')
```

**Comment by bdhingra** [comment]
Hi,

Sorry, thats my mistake. The full prefix for running on CPU should be - 

`THEANO_FLAGS=device=cpu,floatX=float32`

I will update the README.

Best,
Bhuwan
